language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Release
        - OPENSSL_ROOT_DIR=/usr/local/opt/openssl/

    - os: osx
      sudo: required
      env: 
        - TYPE=Debug
        - OPENSSL_ROOT_DIR=/usr/local/opt/openssl/
    
before_install:
  - eval "${MATRIX_EVAL}"
  - git clone -bv0.1 https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_packages.sh
  - bash ./emp-readme/scripts/install_relic.sh
  - bash ./emp-readme/scripts/install_emp-tool.sh
  - bash ./emp-readme/scripts/install_emp-ot.sh

script:
  - cat /proc/cpuinfo || true
  - cmake -DCMAKE_BUILD_TYPE=$TYPE . && make
  - ./run ./bin/sha1 12345
  - ./run ./bin/sha256 12345
